/* The following code was generated by JFlex 1.4.3 on 7/24/15 11:32 AM */

package org.kevoree.modeling;
import com.intellij.lexer.*;
import com.intellij.psi.tree.IElementType;
import static org.kevoree.modeling.idea.psi.MetaModelTypes.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 7/24/15 11:32 AM from the specification file
 * <tt>/Users/duke/Documents/dev/kevoree-modeling/org.kevoree.modeling.idea/org.kevoree.modeling.idea/src/org/kevoree/modeling/_MetaModelLexer.flex</tt>
 */
public class _MetaModelLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\2\1\0\1\1\1\1\22\0\1\1\1\0\1\12"+
    "\4\0\1\10\1\51\1\52\1\35\1\0\1\45\1\4\1\6\1\3"+
    "\12\5\1\44\1\0\1\53\1\46\1\56\2\0\2\7\1\60\1\7"+
    "\1\54\1\55\5\7\1\43\2\7\1\37\2\7\1\42\3\7\1\25"+
    "\1\31\3\7\1\0\1\11\2\0\1\7\1\0\1\30\1\7\1\26"+
    "\1\40\1\14\1\24\1\7\1\33\1\17\1\7\1\22\1\27\1\23"+
    "\1\21\1\20\1\36\1\7\1\15\1\16\1\32\1\34\1\13\1\57"+
    "\1\7\1\41\1\7\1\47\1\0\1\50\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\4"+
    "\2\1\15\4\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\1\1\4\1\16\1\5\1\0\1\17\3\0"+
    "\17\4\1\0\3\4\1\20\11\4\1\21\3\4\1\0"+
    "\2\4\1\22\1\23\6\4\1\24\1\25\4\4\1\0"+
    "\1\26\2\4\1\27\4\4\1\30\3\4\1\0\2\4"+
    "\1\31\6\4\1\0\1\32\2\4\1\33\4\4\1\34"+
    "\6\4\1\35\4\4\1\36\1\4\1\37\1\40\2\4"+
    "\1\41\5\4\1\42\4\4\1\43";

  private static int [] zzUnpackAction() {
    int [] result = new int[151];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\304\0\365\0\u0126\0\u0126"+
    "\0\u0157\0\u0188\0\u01b9\0\u01ea\0\u021b\0\u024c\0\u027d\0\u02ae"+
    "\0\u02df\0\u0310\0\u0341\0\u0372\0\u03a3\0\u03d4\0\u0405\0\61"+
    "\0\61\0\61\0\61\0\61\0\61\0\61\0\u0436\0\u0467"+
    "\0\u0498\0\u04c9\0\u0157\0\61\0\u04fa\0\u0188\0\u052b\0\u055c"+
    "\0\u058d\0\u05be\0\u05ef\0\u0620\0\u0651\0\u0682\0\u06b3\0\u06e4"+
    "\0\u0715\0\u0746\0\u0777\0\u07a8\0\u07d9\0\u080a\0\u083b\0\u086c"+
    "\0\u089d\0\u08ce\0\u08ff\0\u0930\0\u0961\0\u0992\0\u09c3\0\u09f4"+
    "\0\u0a25\0\u0a56\0\u0a87\0\u0ab8\0\u0126\0\u0ae9\0\u0b1a\0\u0b4b"+
    "\0\u0b7c\0\u0bad\0\u0bde\0\u0126\0\u0126\0\u0c0f\0\u0c40\0\u0c71"+
    "\0\u0ca2\0\u0cd3\0\u0d04\0\u0126\0\u0126\0\u0d35\0\u0d66\0\u0d97"+
    "\0\u0dc8\0\u0df9\0\u0126\0\u0e2a\0\u0e5b\0\u0126\0\u0e8c\0\u0ebd"+
    "\0\u0eee\0\u0f1f\0\u0126\0\u0f50\0\u0f81\0\u0fb2\0\u0fe3\0\u1014"+
    "\0\u1045\0\u0126\0\u1076\0\u10a7\0\u10d8\0\u1109\0\u113a\0\u116b"+
    "\0\u119c\0\u0126\0\u11cd\0\u11fe\0\u0126\0\u122f\0\u1260\0\u1291"+
    "\0\u12c2\0\61\0\u12f3\0\u1324\0\u1355\0\u1386\0\u13b7\0\u13e8"+
    "\0\u0126\0\u1419\0\u144a\0\u147b\0\u14ac\0\u0126\0\u14dd\0\u0126"+
    "\0\u0126\0\u150e\0\u153f\0\u0126\0\u1570\0\u15a1\0\u15d2\0\u1603"+
    "\0\u1634\0\u0126\0\u1665\0\u1696\0\u16c7\0\u16f8\0\u0126";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[151];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\2\1\12\1\13\1\14\1\15\1\10\1\16\1\17"+
    "\1\20\1\21\1\10\1\22\1\10\1\23\1\10\1\24"+
    "\1\10\1\25\3\10\1\26\1\10\1\27\3\10\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\2\10"+
    "\1\2\1\10\1\40\62\0\2\3\61\0\1\41\61\0"+
    "\1\10\1\6\2\10\3\0\31\10\10\0\2\10\1\0"+
    "\2\10\4\0\1\10\1\6\1\42\1\10\3\0\31\10"+
    "\10\0\2\10\1\0\2\10\4\0\4\10\3\0\31\10"+
    "\10\0\2\10\1\0\2\10\10\43\1\44\1\45\47\43"+
    "\11\46\1\47\1\44\46\46\4\0\4\10\3\0\1\10"+
    "\1\50\27\10\10\0\2\10\1\0\2\10\4\0\4\10"+
    "\3\0\6\10\1\51\22\10\10\0\2\10\1\0\2\10"+
    "\4\0\4\10\3\0\1\10\1\52\27\10\10\0\2\10"+
    "\1\0\2\10\4\0\4\10\3\0\6\10\1\53\22\10"+
    "\10\0\2\10\1\0\2\10\4\0\4\10\3\0\21\10"+
    "\1\54\1\10\1\55\5\10\10\0\2\10\1\0\2\10"+
    "\4\0\4\10\3\0\1\10\1\56\27\10\10\0\2\10"+
    "\1\0\2\10\4\0\4\10\3\0\10\10\1\57\20\10"+
    "\10\0\2\10\1\0\2\10\4\0\4\10\3\0\2\10"+
    "\1\60\16\10\1\61\7\10\10\0\2\10\1\0\2\10"+
    "\4\0\4\10\3\0\14\10\1\62\14\10\10\0\2\10"+
    "\1\0\2\10\4\0\4\10\3\0\17\10\1\63\11\10"+
    "\10\0\2\10\1\0\2\10\4\0\4\10\3\0\1\10"+
    "\1\64\27\10\10\0\2\10\1\0\2\10\4\0\4\10"+
    "\3\0\2\10\1\65\26\10\10\0\2\10\1\0\2\10"+
    "\4\0\4\10\3\0\1\10\1\66\27\10\10\0\2\10"+
    "\1\0\2\10\53\0\1\67\11\0\4\10\3\0\27\10"+
    "\1\70\1\10\10\0\2\10\1\0\2\10\2\41\1\0"+
    "\56\41\4\0\1\10\1\42\2\10\3\0\31\10\10\0"+
    "\2\10\1\0\2\10\2\43\1\0\56\43\2\46\1\0"+
    "\56\46\4\0\4\10\3\0\2\10\1\71\26\10\10\0"+
    "\2\10\1\0\2\10\4\0\4\10\3\0\21\10\1\72"+
    "\7\10\10\0\2\10\1\0\2\10\4\0\4\10\3\0"+
    "\11\10\1\73\17\10\10\0\2\10\1\0\2\10\4\0"+
    "\4\10\3\0\11\10\1\74\11\10\1\75\5\10\10\0"+
    "\2\10\1\0\2\10\4\0\4\10\3\0\17\10\1\76"+
    "\11\10\10\0\2\10\1\0\2\10\4\0\4\10\3\0"+
    "\23\10\1\77\5\10\10\0\2\10\1\0\2\10\4\0"+
    "\4\10\3\0\31\10\10\0\2\10\1\0\1\100\1\10"+
    "\4\0\4\10\3\0\11\10\1\101\17\10\10\0\2\10"+
    "\1\0\2\10\4\0\4\10\3\0\5\10\1\102\23\10"+
    "\10\0\2\10\1\0\2\10\4\0\4\10\3\0\6\10"+
    "\1\103\22\10\10\0\2\10\1\0\2\10\4\0\4\10"+
    "\3\0\15\10\1\104\13\10\10\0\2\10\1\0\2\10"+
    "\4\0\4\10\3\0\17\10\1\105\11\10\10\0\2\10"+
    "\1\0\2\10\4\0\4\10\3\0\10\10\1\106\20\10"+
    "\10\0\2\10\1\0\2\10\4\0\4\10\3\0\1\10"+
    "\1\107\27\10\10\0\2\10\1\0\2\10\4\0\4\10"+
    "\3\0\23\10\1\110\5\10\10\0\2\10\1\0\2\10"+
    "\54\0\1\111\10\0\4\10\3\0\30\10\1\112\10\0"+
    "\2\10\1\0\2\10\4\0\4\10\3\0\3\10\1\113"+
    "\25\10\10\0\2\10\1\0\2\10\4\0\4\10\3\0"+
    "\10\10\1\114\20\10\10\0\2\10\1\0\2\10\4\0"+
    "\4\10\3\0\22\10\1\115\6\10\10\0\2\10\1\0"+
    "\2\10\4\0\4\10\3\0\1\10\1\116\27\10\10\0"+
    "\2\10\1\0\2\10\4\0\4\10\3\0\21\10\1\117"+
    "\7\10\10\0\2\10\1\0\2\10\4\0\4\10\3\0"+
    "\23\10\1\120\5\10\10\0\2\10\1\0\2\10\4\0"+
    "\4\10\3\0\5\10\1\121\23\10\10\0\2\10\1\0"+
    "\2\10\4\0\4\10\3\0\14\10\1\122\14\10\10\0"+
    "\2\10\1\0\2\10\4\0\4\10\3\0\12\10\1\123"+
    "\16\10\10\0\2\10\1\0\2\10\4\0\4\10\3\0"+
    "\10\10\1\124\20\10\10\0\2\10\1\0\2\10\4\0"+
    "\4\10\3\0\13\10\1\125\15\10\10\0\2\10\1\0"+
    "\2\10\4\0\4\10\3\0\3\10\1\126\25\10\10\0"+
    "\2\10\1\0\2\10\4\0\4\10\3\0\23\10\1\127"+
    "\5\10\10\0\2\10\1\0\2\10\4\0\4\10\3\0"+
    "\13\10\1\130\15\10\10\0\2\10\1\0\2\10\4\0"+
    "\4\10\3\0\1\10\1\131\27\10\10\0\2\10\1\0"+
    "\2\10\37\0\1\132\25\0\4\10\3\0\31\10\10\0"+
    "\1\10\1\133\1\0\2\10\4\0\4\10\3\0\4\10"+
    "\1\134\24\10\10\0\2\10\1\0\2\10\4\0\4\10"+
    "\3\0\2\10\1\135\26\10\10\0\2\10\1\0\2\10"+
    "\4\0\4\10\3\0\17\10\1\136\11\10\10\0\2\10"+
    "\1\0\2\10\4\0\4\10\3\0\21\10\1\137\7\10"+
    "\10\0\2\10\1\0\2\10\4\0\4\10\3\0\3\10"+
    "\1\140\25\10\10\0\2\10\1\0\2\10\4\0\4\10"+
    "\3\0\4\10\1\141\24\10\10\0\2\10\1\0\2\10"+
    "\4\0\4\10\3\0\1\10\1\142\27\10\10\0\2\10"+
    "\1\0\2\10\4\0\4\10\3\0\3\10\1\143\25\10"+
    "\10\0\2\10\1\0\2\10\4\0\4\10\3\0\5\10"+
    "\1\144\23\10\10\0\2\10\1\0\2\10\4\0\4\10"+
    "\3\0\4\10\1\145\24\10\10\0\2\10\1\0\2\10"+
    "\4\0\4\10\3\0\6\10\1\146\22\10\10\0\2\10"+
    "\1\0\2\10\55\0\1\147\7\0\4\10\3\0\5\10"+
    "\1\150\23\10\10\0\2\10\1\0\2\10\4\0\4\10"+
    "\3\0\16\10\1\151\12\10\10\0\2\10\1\0\2\10"+
    "\4\0\4\10\3\0\17\10\1\152\11\10\10\0\2\10"+
    "\1\0\2\10\4\0\4\10\3\0\4\10\1\153\24\10"+
    "\10\0\2\10\1\0\2\10\4\0\4\10\3\0\6\10"+
    "\1\154\22\10\10\0\2\10\1\0\2\10\4\0\4\10"+
    "\3\0\2\10\1\155\26\10\10\0\2\10\1\0\2\10"+
    "\4\0\4\10\3\0\2\10\1\156\26\10\10\0\2\10"+
    "\1\0\2\10\4\0\4\10\3\0\3\10\1\157\25\10"+
    "\10\0\2\10\1\0\2\10\4\0\4\10\3\0\25\10"+
    "\1\160\3\10\10\0\2\10\1\0\2\10\56\0\1\161"+
    "\6\0\4\10\3\0\6\10\1\162\22\10\10\0\2\10"+
    "\1\0\2\10\4\0\4\10\3\0\4\10\1\163\24\10"+
    "\10\0\2\10\1\0\2\10\4\0\4\10\3\0\17\10"+
    "\1\164\11\10\10\0\2\10\1\0\2\10\4\0\4\10"+
    "\3\0\1\10\1\165\27\10\10\0\2\10\1\0\2\10"+
    "\4\0\4\10\3\0\3\10\1\166\25\10\10\0\2\10"+
    "\1\0\2\10\4\0\4\10\3\0\15\10\1\167\13\10"+
    "\10\0\2\10\1\0\2\10\4\0\4\10\3\0\4\10"+
    "\1\170\24\10\10\0\2\10\1\0\2\10\4\0\4\10"+
    "\3\0\1\10\1\171\27\10\10\0\2\10\1\0\2\10"+
    "\56\0\1\172\6\0\4\10\3\0\17\10\1\173\11\10"+
    "\10\0\2\10\1\0\2\10\4\0\4\10\3\0\1\10"+
    "\1\174\27\10\10\0\2\10\1\0\2\10\4\0\4\10"+
    "\3\0\4\10\1\175\24\10\10\0\2\10\1\0\2\10"+
    "\4\0\4\10\3\0\14\10\1\176\14\10\10\0\2\10"+
    "\1\0\2\10\4\0\4\10\3\0\5\10\1\177\23\10"+
    "\10\0\2\10\1\0\2\10\4\0\4\10\3\0\6\10"+
    "\1\200\22\10\10\0\2\10\1\0\2\10\4\0\4\10"+
    "\3\0\20\10\1\201\10\10\10\0\2\10\1\0\2\10"+
    "\4\0\4\10\3\0\24\10\1\202\4\10\10\0\2\10"+
    "\1\0\2\10\4\0\4\10\3\0\5\10\1\203\23\10"+
    "\10\0\2\10\1\0\2\10\4\0\4\10\3\0\27\10"+
    "\1\204\1\205\10\0\2\10\1\0\2\10\4\0\4\10"+
    "\3\0\6\10\1\206\22\10\10\0\2\10\1\0\2\10"+
    "\4\0\4\10\3\0\13\10\1\207\15\10\10\0\2\10"+
    "\1\0\2\10\4\0\4\10\3\0\11\10\1\210\17\10"+
    "\10\0\2\10\1\0\2\10\4\0\4\10\3\0\6\10"+
    "\1\211\22\10\10\0\2\10\1\0\2\10\4\0\4\10"+
    "\3\0\1\10\1\212\27\10\10\0\2\10\1\0\2\10"+
    "\4\0\4\10\3\0\4\10\1\213\24\10\10\0\2\10"+
    "\1\0\2\10\4\0\4\10\3\0\26\10\1\214\2\10"+
    "\10\0\2\10\1\0\2\10\4\0\4\10\3\0\3\10"+
    "\1\215\25\10\10\0\2\10\1\0\2\10\4\0\4\10"+
    "\3\0\10\10\1\216\20\10\10\0\2\10\1\0\2\10"+
    "\4\0\4\10\3\0\5\10\1\217\23\10\10\0\2\10"+
    "\1\0\2\10\4\0\4\10\3\0\4\10\1\220\24\10"+
    "\10\0\2\10\1\0\2\10\4\0\4\10\3\0\14\10"+
    "\1\221\14\10\10\0\2\10\1\0\2\10\4\0\4\10"+
    "\3\0\17\10\1\222\11\10\10\0\2\10\1\0\2\10"+
    "\4\0\4\10\3\0\21\10\1\223\7\10\10\0\2\10"+
    "\1\0\2\10\4\0\4\10\3\0\17\10\1\224\11\10"+
    "\10\0\2\10\1\0\2\10\4\0\4\10\3\0\4\10"+
    "\1\225\24\10\10\0\2\10\1\0\2\10\4\0\4\10"+
    "\3\0\5\10\1\226\23\10\10\0\2\10\1\0\2\10"+
    "\4\0\4\10\3\0\6\10\1\227\22\10\10\0\2\10"+
    "\1\0\2\10";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5929];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\25\1\7\11\4\1\1\0\1\11\3\0"+
    "\17\1\1\0\21\1\1\0\20\1\1\0\14\1\1\0"+
    "\11\1\1\0\10\1\1\11\35\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[151];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
  public _MetaModelLexer() {
    this((java.io.Reader)null);
  }


  public _MetaModelLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public _MetaModelLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 154) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 8: 
          { return COMMA;
          }
        case 36: break;
        case 29: 
          { return INFER_WITH;
          }
        case 37: break;
        case 19: 
          { return MREF;
          }
        case 38: break;
        case 14: 
          { return COMMENT;
          }
        case 39: break;
        case 31: 
          { return OPPOSITE;
          }
        case 40: break;
        case 21: 
          { return FUNC;
          }
        case 41: break;
        case 25: 
          { return OUTPUT;
          }
        case 42: break;
        case 17: 
          { return ATT;
          }
        case 43: break;
        case 28: 
          { return EOF;
          }
        case 44: break;
        case 1: 
          { return com.intellij.psi.TokenType.BAD_CHARACTER;
          }
        case 45: break;
        case 32: 
          { return KMF_VERSION;
          }
        case 46: break;
        case 3: 
          { return SUB;
          }
        case 47: break;
        case 11: 
          { return BODY_CLOSE;
          }
        case 48: break;
        case 13: 
          { return ANNOT_PARAM_CLOSE;
          }
        case 49: break;
        case 27: 
          { return NEWLINE;
          }
        case 50: break;
        case 7: 
          { return COLON;
          }
        case 51: break;
        case 23: 
          { return INPUT;
          }
        case 52: break;
        case 10: 
          { return BODY_OPEN;
          }
        case 53: break;
        case 33: 
          { return DEPENDENCY;
          }
        case 54: break;
        case 16: 
          { return REF;
          }
        case 55: break;
        case 26: 
          { return VERSION;
          }
        case 56: break;
        case 20: 
          { return FROM;
          }
        case 57: break;
        case 9: 
          { return EQ;
          }
        case 58: break;
        case 35: 
          { return TEMPORAL_RESOLUTION;
          }
        case 59: break;
        case 15: 
          { return STRING;
          }
        case 60: break;
        case 22: 
          { return CRLF;
          }
        case 61: break;
        case 18: 
          { return ENUM;
          }
        case 62: break;
        case 30: 
          { return PRECISION;
          }
        case 63: break;
        case 24: 
          { return CLASS;
          }
        case 64: break;
        case 12: 
          { return ANNOT_PARAM_OPEN;
          }
        case 65: break;
        case 4: 
          { return IDENT;
          }
        case 66: break;
        case 5: 
          { return NUMBER;
          }
        case 67: break;
        case 6: 
          { return MULT_SEP;
          }
        case 68: break;
        case 34: 
          { return TEMPORAL_LIMIT;
          }
        case 69: break;
        case 2: 
          { return com.intellij.psi.TokenType.WHITE_SPACE;
          }
        case 70: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
